### ISSUE TITLE
Which "environment" do I set so I can tabout of single square brackets?

### ISSUE THREAD

**Issue by ReaderGuy42** [phibr0/obsidian-tabout#3]
### Describe the feature

I would like to be able to tabout of single square brackets [ ], but don't know what environment to set to get it to work. 

Thanks :)

### Does this fix a problem? If so, specify.

Wanting to escape single brackets.

**Comment by phibr0** [comment]
The new Update includes a Command to detect the Environment your cursor is in. Use it from the Command Palette

**Comment by ReaderGuy42** [comment]
Ok great, that works! But when I do this for regular parenthesis ( ) nothing happens. Is it possible for these as well?
Thank you!!

**Comment by phibr0** [comment]
There might not be an environment, it should work if you leave it empty though

**Comment by ReaderGuy42** [comment]
If I leave the environment blank it tells me that "Something is still missing" :)

**Comment by phibr0** [comment]
I will take a look later today

**Comment by ReaderGuy42** [comment]
Ok, great, thank you!!

**Comment by ReaderGuy42** [comment]
Fantastic, thank you so much :)
