### ISSUE TITLE
[Bug]: In new Live Preview mode Tabout causes whole paragraph to indent

### ISSUE THREAD

**Issue by ReaderGuy42** [phibr0/obsidian-tabout#6]
### Describe the bug

In the new Live Preview mode (that went public yesterday, I think) trying to tab out of e.g. parentheses causes that whole paragraph to indent, causing it to become code formatted.

### Steps to reproduce

Activate Live Preview mode, write using whatever rule you have for Tabout, then hit tab key, see that it indents the whole paragraph and doesn't actually "tabout".

### Expected Behavior

Tab out of parentheses/asterisks, etc. 

### Operating system

Linux

**Comment by phibr0** [comment]
see #7

**Comment by phibr0** [comment]
(The indentation is default tab behaviour in Obsidian)
