### ISSUE TITLE
[Bug]: Only works in legacy mode

### ISSUE THREAD

**Issue by Hunanbean** [phibr0/obsidian-tabout#7]
### Describe the bug

The plugin does not function in regular mode. Works amazingly well in legacy mode.

Thank you

### Steps to reproduce

Attempt to use plugin in regular mode, watch it not work.
Switch to legacy mode, watch it work.

### Expected Behavior

Expected to work in regular mode.

### Operating system

Linux

**Comment by phibr0** [comment]
I am working on it! Unfortunately for it to work in the new Editor I need to completely rewrite the Plugin...

**Comment by Hunanbean** [comment]
Understood. I will just continue to use Legacy mode for now, as i consider this plugin essential.

Thanks!

**Comment by ReaderGuy42** [comment]
I just wanted to add my support, that I too think this plugin is essential! Thanks :)

**Comment by phibr0** [comment]
Just released the new update! It works now in both modes.

**Comment by ReaderGuy42** [comment]
> Just released the new update! It works now in both modes.

You're awesome!! Thank you so much :)
